# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c76771dc27e47636fc382c393f58c500d758922081cdfe70a0006a6e2e9768411d2a1be6425e8f7260da5172dd23b26cee36ccc713b82a06305d272320d99b9

test:
  secret_key_base: e4bf7f8fc2b2f0fa79ab818b581a9b4006dfc33fadf56d5c301f55b25de117474ec1d0d79df5b9dd398cd8ae1fd48e4e50af3bffa5d08225c9d89d7a33534f7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
